version: "3.8"

services:
  voting-app:
    image: voting-app
    container_name: voting_app_container
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9321:9321"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: user-name
      SPRING_DATASOURCE_PASSWORD: strong-password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 

volumes:
  local_pgdata:
  pgadmin-data:


