# Global settings
nameOverride: ""
fullnameOverride: ""

# Namespace configuration
namespace:
  create: true
  name: voting-app

# PostgreSQL configuration
postgres:
  enabled: true
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: db
    port: 5432
  credentials:
    username: "user-name"
    password: "strong-password"
  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi

# pgAdmin configuration
pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
  credentials:
    email: "user-name@domain-name.com"
    password: "strong-password"
  persistence:
    enabled: true
    storageClass: ""
    size: 512Mi

# Voting application configuration
votingApp:
  enabled: true
  image:
    repository: voting-app
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    httpPort: 8080
    metricsPort: 9321
  prometheus:
    scrape: true
    path: "/actuator/prometheus"
    port: 9321
  env:
    datasourceUrl: "jdbc:postgresql://db:5432/postgres"
    datasourceUsername: "user-name"
    datasourcePassword: "strong-password"
    hibernateDdlAuto: "update"
  hpa:
    enabled: true
  resources:
    requests:
      cpu: "800m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "800Mi"
# HAProxy configuration
haproxy:
  enabled: true
  image:
    repository: haproxy
    tag: "2.4"
    pullPolicy: IfNotPresent
  service:
    port: 80
  config:
    maxconn: 256
    timeoutConnect: "50000s"
    timeoutClient: "500000s"
    timeoutServer: "500000s"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "500"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  hosts:
    - host: voting.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: haproxy-service
          servicePort: 80
    - host: pgadmin.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: pgadmin
          servicePort: 80