spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user-name
    password: strong-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
