{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "voting-app.namespaceName" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
{{- end }}