apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-app.fullname" . }}-credentials
  namespace: {{ include "voting-app.namespaceName" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.credentials.username | b64enc | quote }}
  postgres-password: {{ .Values.postgres.credentials.password | b64enc | quote }}
  pgadmin-email: {{ .Values.pgadmin.credentials.email | b64enc | quote }}
  pgadmin-password: {{ .Values.pgadmin.credentials.password | b64enc | quote }}